apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-and-secrets.yaml
  - storage-class.yaml
  - certificates.yaml
  - postgres.yaml
  - api-gateway.yaml
  - ledger-gateways.yaml
  - submission-services.yaml
  - network-policies.yaml
