apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - certificates.yaml
  - data-services.yaml
  - api-gateway.yaml
  - ledger-gateways.yaml
  - submission-services.yaml
  - history-workers.yaml
  - webapp.yaml
  - network-policies.yaml
