#!/usr/bin/env bash
set -eo pipefail

if [[ $# -ne 1 ]]; then
  echo 'usage: bash Verify-LiveFabric.sh <absolute-generated-test-network-dir>' >&2
  exit 2
fi

network_dir=$(cd "$1" && pwd)
if [[ ! -f "$network_dir/scripts/envVar.sh" || ! -f "$network_dir/configtx/configtx.yaml" ]]; then
  echo 'Expected a generated OSC-Network/test-network checkout' >&2
  exit 1
fi
export TEST_NETWORK_HOME="$network_dir"
export FABRIC_CFG_PATH="$network_dir/../config"
export PATH="$network_dir/../bin:$PATH"
export VERBOSE=false
export OVERRIDE_ORG=
for tool in peer configtxlator python3; do
  command -v "$tool" >/dev/null || { echo "Missing $tool" >&2; exit 1; }
done

# envVar.sh provides the exact admin identities and TLS roots generated by the
# matching two-organization sample network.
source "$network_dir/scripts/envVar.sh"
temp_dir=$(mktemp -d)
trap 'rm -f "$temp_dir/config.block" "$temp_dir/config.json"; rmdir "$temp_dir"' EXIT

for org in 1 2; do
  setGlobals "$org"
  peer channel getinfo -c osc-channel >/dev/null
  committed=$(peer lifecycle chaincode querycommitted --channelID osc-channel --name osc-provenance --output json)
  if ! printf '%s' "$committed" | python3 -c 'import json,sys; d=json.load(sys.stdin); assert d.get("version")=="1.0" and int(d.get("sequence",0))>=1 and d.get("approvals",{}).get("NSGMSP") is True and d.get("approvals",{}).get("CitizenScienceMSP") is True'; then
    echo "osc-provenance is not committed on organization $org" >&2
    exit 1
  fi
  echo "Organization $org: peer channel and committed provenance chaincode OK"
done

setGlobals 1
peer channel fetch config "$temp_dir/config.block" -o localhost:7050 -c osc-channel \
  --tls --cafile "$ORDERER_CA" >/dev/null
configtxlator proto_decode --input "$temp_dir/config.block" --type common.Block \
  --output "$temp_dir/config.json"
python3 - "$temp_dir/config.json" <<'PY'
import json
import sys

with open(sys.argv[1], encoding='utf-8') as source:
    block = json.load(source)
groups = block['data']['data'][0]['payload']['data']['config']['channel_group']['groups']['Application']['groups']
expected = {'NSGMSP', 'CitizenScienceMSP'}
if set(groups) != expected:
    raise SystemExit(f'Unexpected live channel MSP groups: {sorted(groups)}')
print('Live channel MSPs: NSGMSP, CitizenScienceMSP')
PY
